blueye:
  blueye_telemetry:
    ros__parameters:

      # IP address of the Blueye ROV (192.168.1.101)
      drone_ip: '192.168.1.101'

      rate: 10.0

      # Set true to skip the Blueye SDK connection entirely (for offline testing)
      is_simulation: false
