blueye:
  blueye_telemetry:
    ros__parameters:

      # IP address of the Blueye ROV.
      # Leave empty ('') to let the Blueye SDK auto-discover the drone
      # 192.168.1.101 
      drone_ip: ''

      rate: 10.0

      # Set true to skip the Blueye SDK connection entirely (for offline testing)
      is_simulation: false
