blueye: # namespace
  blueye_interface: # node
    ros__parameters:
      # ROS- related params
      rate: 5.0 #Hz
      is_simulation: False
      
      # Blueye ROV-related params
      # Camera params 
      #camera_bitrate: 6000000 # type: integer, range:1 000 000 - 16 000 000, unit: bits
      camera_bitrate_min: 1000000 
      camera_bitrate_max: 16000000 
      
      #camera_exposure: -1_ # type: int, range: 1 - 5 000, unit: [s], t_exp = N/1000[s], auto: exp=-1
      camera_exposure_min: -1
      camera_exposure_max: 5000
      
      #camera_framerate: 25 # type: int, values:{25, 30}, unit:fps
      camera_framerate_values: [25, 30]
      
      #camera_hue: 0 # type: int, range: -40 - 40, unit: ?
      camera_hue_min: -40
      camera_hue_max: 40      
            
      #camera_is_recording: 0 # type: bool 
      #camera_record_time: -1 # type: int, range: 0 - range(int), unit: [s], t=-1 if not recording
      
      #camera_resolution: 1080 # type: int, values={480, 720,1080} , unit: vertical_pixels
      camera_resolution_values: [480, 720,1080]
            
      #camera_whitebalance: -1 # type: int, range: [2800, 9300], unit: 
      camera_whitebalance_min: 2800 # auto: -1
      camera_whitebalance_max: 9300
      
      #camera_tilt_angle: 0  # type: float64, range: [30, 30], unit: [°] 
      camera_tilt_angle_min: -30
      camera_tilt_angle_max: 30
      
      #camera_tilt_speed: 0 # type: int, range: [-1, 1], unit: [] 
      camera_tilt_speed_min: -1
      camera_tilt_speed_max: 1
      
      
      
            
      
       # type: , range: , unit: 
       # type: , range: , unit: 
       # type: , range: , unit:
        # type: , range: , unit: 
         # type: , range: , unit: 
          # type: , range: , unit: 
           # type: , range: , unit: 
            # type: , range: , unit: 
             # type: , range: , unit: 
             
              
 # type: , range: , unit: 
