rov_data_logger:
  ros__parameters:

    # Directory for output CSV files
    log_dir:  ~/ros2_ws/rov_logs

    # How often to write a row [Hz]
    log_rate: 1.0

    # Blueye sensors 
    log_blueye_depth:        true
    log_blueye_imu:          true
    log_blueye_battery:      true
    log_blueye_altitude:     true    
    log_blueye_water_temp:   true    

    # External GNSS + heading 
    log_gnss_fix:            false  
    log_heading:             false   

    # WaterLinked UWGPS 
    log_uwgps_relative:      false  
    log_uwgps_ned:           false
    log_uwgps_global:        false