rov_data_logger:
  ros__parameters:

    # Directory for output CSV files
    log_dir:  ~/ros2_ws/rov_logs

    # Full log rate [Hz] - all topics
    log_rate: 1.0

    # Nav log rate [Hz] - depth, IMUs, attitude, UWGPS
    nav_log_rate: 10.0

    # Blueye sensors 
    log_blueye_depth:               true
    log_blueye_imu_calibrated:      true   
    log_blueye_imu1:                true   
    log_blueye_imu2:                true   
    log_blueye_attitude:            true   
    log_blueye_battery:             true
    log_blueye_water_temp:          true
    log_blueye_canister:            true   
    log_blueye_control_force:       true
    log_blueye_control_mode:        true
    log_blueye_controller_health:   true
    log_blueye_magnetic_declination: true
    log_blueye_cpu_temp:            true
    log_blueye_dive_time:           true

    # External GNSS + heading   
    log_gnss_fix:                   false
    log_heading:                    false

    # WaterLinked UWGPS   
    log_uwgps_relative:             true
    log_uwgps_ned:                  true
    log_uwgps_global:               true
